### ISSUE TITLE
Weights_trained wanted

### ISSUE THREAD

**Issue by zeliangzong** [ybabakhin/kaggle_salt_bes_phalanx#4]
Thank for your open code,so I could learn lots thing from it. But when i run it on my machine,i find that training models needs looooooong time.so could you please give your own weights to me?Looking forward to your early reply.

**Comment by ybabakhin** [comment]
Ok, we've decided to share the final weights as well.

Here is the link to google drive: https://drive.google.com/file/d/12iXDUhBTC6596MLAC2aiN-GDVqBbGBWh/view?usp=sharing

And I will update README shortly.

**Comment by ybabakhin** [comment]
Updated README: https://github.com/ybabakhin/kaggle_salt_bes_phalanx/commit/eebc79bc9175c455c450a673207c6c937b55419a
